language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
script: "bundle exec rake spec"
before_install: # Need to install npm to test js
- sudo apt-get update
- sudo apt-get install npm
- npm install jasmine-node@1.14.2
gemfile:
  - gemfiles/i18n_0_6.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
